name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (Spring Boot typically uses Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: mvn test -Dtest=\!LoginUITest,\!AddWasteLogUITest

      # Step 5: Run Integration / Automation Tests
      - name: Run Integration Tests
        run: mvn verify -Dtest=\!LoginUITest,\!AddWasteLogUITest
